# Generated by Django 3.1.4 on 2020-12-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201208_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/images/portfolio', verbose_name='Изображение'),
        ),
    ]
